# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/josecoelho/Documents/IST/PSD/Labs/Lab3/psd-proj3/Lab3.srcs/sources_1/ip/train_features/train_features.xci
# IP: The module: 'train_features' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/josecoelho/Documents/IST/PSD/Labs/Lab3/psd-proj3/Lab3.srcs/sources_1/ip/train_features/train_features_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'train_features'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/josecoelho/Documents/IST/PSD/Labs/Lab3/psd-proj3/Lab3.srcs/sources_1/ip/train_features/train_features.xci
# IP: The module: 'train_features' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/josecoelho/Documents/IST/PSD/Labs/Lab3/psd-proj3/Lab3.srcs/sources_1/ip/train_features/train_features_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'train_features'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
